server:
  port: 8989
  servlet:
    context-path: /ems
    jsp:
      init-parameters:
        development: true
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ems_pink?charcaterEncoding=utf-8
    username: root
    password: 520314
  redis:
    host: 59.110.234.46
    port: 7000
    database: 3
mybatis:
  mapper-locations: classpath:com/zhang/mapper/*.xml
  type-aliases-package: com.zhang.entity